<script setup>
import { computed, onMounted, ref } from 'vue'
import { api, demoBenches, demoProducts, demoProjects, demoQuotes, demoTemplates, demoUsers, getCurrentUserId, setCurrentUserId } from './services/api'

const API_URL = import.meta.env.VITE_API_URL || '/api'
const page = ref('dashboard')
const projects = ref([])
const products = ref([])
const quotes = ref([])
const benches = ref([])
const templates = ref([])
const users = ref([])
const files = ref([])
const currentFolder = ref('')
const apiOffline = ref(false)
const search = ref('')
const toast = ref('')
const summary = ref({ projects: 2, activeQuotes: 1, documents: 24, teamMembers: 2 })
const showProjectModal = ref(false)
const showProductModal = ref(false)
const showBenchModal = ref(false)
const showProjectDetails = ref(false)
const showQuoteModal = ref(false)
const showTemplateModal = ref(false)
const editingProject = ref(null)
const editingProduct = ref(null)
const editingBench = ref(null)
const editingQuote = ref(null)
const editingTemplate = ref(null)
const projectDetails = ref(null)
const productDetails = ref(null)
const projectActivity = ref([])
const benchDetails = ref(null)
const equipmentSummaries = ref({})
const quoteEquipmentSummary = ref(null)
const currentUserId = ref(Number(getCurrentUserId()))
const projectForm = ref({ projectNumber: '', name: '', contactPerson: '', description: '', status: 'ACTIVE' })
const productForm = ref({ projectId: null, productNumber: '', name: '', description: '', presentation: '', assemblyElements: '', assemblySteps: '', presentationImages: [], enclosureImages: [], enclosurePinout: '', pcbImages: [], pcbSpecifications: '', contacts: [] })
const benchForm = ref({ name: '', description: '', location: '', equipment: [], terminals: [] })
const templateForm = ref({ name: '', description: '', language: 'CPP', content: '' })
const quoteForm = ref({ productId: null, benchId: null, templateId: null, name: '', description: '', status: 'DRAFT', references: [], steps: [] })
const templateTokens = '{{TEST_CLASS}}, {{STEPS}}'
const templateTokensFull = '{{QUOTE_ID}}, {{PRODUCT_NUMBER}}, {{PRODUCT_NAME}}, {{STEP_NUMBER}}, {{VERIFICATION_TYPE}}, {{START_CONDITION}}, {{GROUND_REFERENCE}}, {{PIN_TO_TEST}}, {{TEST_METHOD}}, {{MEASUREMENT_METHOD}}, {{WAIT_MS}}, {{EXPECTED_MIN}}, {{EXPECTED_MAX}}, {{UNIT}}, {{POWER_SUPPLY}}, {{SUPPLY_VOLTAGE}}, {{SUPPLY_CURRENT}}, {{RELAY_CHANNELS}}, {{RELAY_DELAY_MS}}'

const activeUser = computed(() => users.value.find(user => Number(user.id) === Number(currentUserId.value)) ||
  { displayName: 'Alex Martin', role: 'ADMIN' })

const projectQuotes = computed(() => {
  if (!projectDetails.value) return []
  return quotes.value.filter(quote => quote.projectId === projectDetails.value.id ||
    (!quote.projectId && quote.projectNumber === projectDetails.value.projectNumber))
})

const projectProducts = computed(() => {
  if (!projectDetails.value) return []
  return products.value.filter(product => Number(product.projectId) === Number(projectDetails.value.id))
})

const navItems = [
  { id: 'dashboard', label: 'Vue d’ensemble', icon: '⌂' },
  { id: 'projects', label: 'Projets', icon: '▦' },
  { id: 'products', label: 'Produits', icon: '◈' },
  { id: 'benches', label: 'Bancs de test', icon: '⌘' },
  { id: 'templates', label: 'Templates C++', icon: 'T' },
  { id: 'documents', label: 'Documentation', icon: '▤' },
]

const filteredProjects = computed(() => projects.value.filter(project =>
  `${project.projectNumber} ${project.name} ${project.contactPerson || ''}`.toLowerCase().includes(search.value.toLowerCase())))

function emptyStep(stepNumber = 1) {
  return { stepNumber, subStep: 1, verificationType: 'B', startCondition: '', groundReference: '', pinToTest: '', measurementType: 'CURRENT', unit: 'mA', expectedMin: null, expectedMax: null, relay: '', voltage: null, notes: '', powerSupplyName: '', supplyVoltage: null, supplyCurrent: null, relayChannels: '', relayDelayMs: null, testMethod: '', measurementMethod: '', waitMs: null, requiredInstruments: '', testTemplateId: null }
}

function defaultTemplateContent() {
  return '// Generated by MegaFinder - Test quote #{{QUOTE_ID}}\n#include <gtest/gtest.h>\n\nclass {{TEST_CLASS}} : public ::testing::Test {};\n\n{{STEPS}}'
}

async function loadData() {
  try {
    const [projectData, productData, quoteData, benchData, userData, summaryData, templateData] = await Promise.all([
      api('/projects'), api('/products'), api('/test-quotes'), api('/test-benches'), api('/users'), api('/dashboard/summary'), api('/test-templates'),
    ])
    projects.value = projectData; products.value = productData; quotes.value = quoteData; benches.value = benchData; users.value = userData; templates.value = templateData; summary.value = summaryData; apiOffline.value = false
    await loadFiles()
  } catch {
    apiOffline.value = true; projects.value = demoProjects; products.value = demoProducts; quotes.value = demoQuotes; benches.value = demoBenches; templates.value = demoTemplates; users.value = demoUsers
  }
}

async function loadFiles(folder = currentFolder.value) {
  currentFolder.value = folder
  try { files.value = (await api(`/files?path=${encodeURIComponent(folder)}`)).items } catch { files.value = demoFiles(folder) }
}

function demoFiles(folder) {
  if (folder) return [{ name: 'README.md', type: 'file', extension: 'md', path: `${folder}/README.md`, openUri: '' }]
  return [{ name: 'projets', type: 'directory', extension: '', path: 'projets', openUri: '' }, { name: 'README.md', type: 'file', extension: 'md', path: 'README.md', openUri: '' }]
}

function fileSystemPath(file) {
  const uri = file.openUri || ''
  const rawPath = uri.startsWith('file:///') ? uri.slice('file:///'.length) : uri
  const path = decodeURIComponent(rawPath)
  return /^[A-Za-z]:\//.test(path) ? path.replaceAll('/', '\\') : path
}

function openFile(file) {
  if (file.type === 'directory') return loadFiles(file.path)
  if (file.openUri) window.open(file.openUri, '_blank', 'noopener,noreferrer')
  else copyFilePath(file)
}

async function copyFilePath(file) {
  const path = fileSystemPath(file)
  try { await navigator.clipboard.writeText(path); notify('Chemin local copié') } catch { notify(`Chemin local : ${path}`) }
}

function openProjectModal(project = null) {
  editingProject.value = project
  projectForm.value = project ? { ...project } : { projectNumber: '', name: '', contactPerson: '', description: '', status: 'ACTIVE' }
  showProjectModal.value = true
}

function emptyContact() { return { name: '', role: '', email: '', phone: '' } }

function openProductModal(product = null, project = null) {
  editingProduct.value = product
  productForm.value = product ? {
    projectId: product.projectId, productNumber: product.productNumber, name: product.name,
    description: product.description || '', presentation: product.presentation || '', assemblyElements: product.assemblyElements || '', assemblySteps: product.assemblySteps || '',
    presentationImagesText: (product.presentationImages || []).join('\n'),
    enclosureImagesText: (product.enclosureImages || []).join('\n'), enclosurePinout: product.enclosurePinout || '',
    pcbImagesText: (product.pcbImages || []).join('\n'), pcbSpecifications: product.pcbSpecifications || '',
    contacts: product.contacts ? product.contacts.map(contact => ({ ...contact })) : [emptyContact()],
  } : {
    projectId: project?.id || projectDetails.value?.id || projects.value[0]?.id || null,
    productNumber: '', name: '', description: '', presentation: '', assemblyElements: '', assemblySteps: '', presentationImagesText: '',
    enclosureImagesText: '', enclosurePinout: '', pcbImagesText: '', pcbSpecifications: '', contacts: [emptyContact()],
  }
  showProductModal.value = true
}

async function openProductDetails(product) {
  page.value = 'product-detail'
  productDetails.value = product
  if (apiOffline.value) {
    productDetails.value = { ...(demoProducts.find(item => item.id === product.id) || product), quotes: demoQuotes.filter(quote => Number(quote.productId || 1) === Number(product.id)) }
    equipmentSummaries.value = {}
    return
  }
  try {
    productDetails.value = await api(`/products/${product.id}`)
    const summaryResults = await Promise.allSettled((productDetails.value.quotes || []).map(quote => api(`/test-quotes/${quote.id}/equipment-summary`)))
    equipmentSummaries.value = Object.fromEntries((productDetails.value.quotes || []).map((quote, index) => [quote.id, summaryResults[index].status === 'fulfilled' ? summaryResults[index].value : null]))
  }
  catch { notify('Impossible de charger le produit') }
}

async function decodeQuoteEquipment(quote) {
  if (apiOffline.value) return notify('Mode présentation : décodage simulé')
  try {
    equipmentSummaries.value = { ...equipmentSummaries.value, [quote.id]: await api(`/test-quotes/${quote.id}/equipment-summary`) }
    notify('Équipement requis décodé')
  } catch { notify('Impossible de décoder les équipements du devis') }
}

function addProductContact() { productForm.value.contacts.push(emptyContact()) }

async function saveProduct() {
  const payload = { ...productForm.value,
    presentationImages: (productForm.value.presentationImagesText || '').split(/\r?\n/).map(value => value.trim()).filter(Boolean),
    enclosureImages: (productForm.value.enclosureImagesText || '').split(/\r?\n/).map(value => value.trim()).filter(Boolean),
    pcbImages: (productForm.value.pcbImagesText || '').split(/\r?\n/).map(value => value.trim()).filter(Boolean),
  }
  delete payload.presentationImagesText; delete payload.enclosureImagesText; delete payload.pcbImagesText
  try {
    if (apiOffline.value) {
      const project = projects.value.find(item => Number(item.id) === Number(payload.projectId))
      const localProduct = { id: editingProduct.value?.id || Date.now(), ...payload, projectNumber: project?.projectNumber, projectName: project?.name, quoteCount: 0, contactCount: payload.contacts.length }
      if (editingProduct.value) Object.assign(editingProduct.value, localProduct); else products.value.unshift(localProduct)
    } else await api(editingProduct.value ? `/products/${editingProduct.value.id}` : '/products', { method: editingProduct.value ? 'PUT' : 'POST', body: JSON.stringify(payload) })
    showProductModal.value = false; await loadData(); notify('Produit enregistré')
  } catch { notify('Impossible d’enregistrer le produit') }
}

async function deleteProduct(product) {
  if (!confirm(`Supprimer ${product.name} et ses devis ?`)) return
  if (!apiOffline.value) await api(`/products/${product.id}`, { method: 'DELETE' })
  products.value = products.value.filter(item => item.id !== product.id)
  if (page.value === 'product-detail') page.value = 'products'
  notify('Produit supprimé')
}

function emptyEquipment(type = 'POWER_SUPPLY') {
  return { equipmentType: type, name: '', quantity: 1, channelCount: 1, voltageMin: null, voltageMax: null, currentMax: null, notes: '' }
}

function emptyTerminal(label = '') {
  return { terminalLabel: label, pinName: '', signalType: '', description: '', relayReference: '', notes: '' }
}

function openBenchModal(bench = null) {
  editingBench.value = bench
  benchForm.value = bench ? {
    name: bench.name, description: bench.description || '', location: bench.location || '',
    equipment: bench.equipment ? bench.equipment.map(item => ({ ...item })) : [],
    terminals: bench.terminals ? bench.terminals.map(item => ({ ...item })) : [],
  } : { name: '', description: '', location: '', equipment: [emptyEquipment()], terminals: [emptyTerminal('X1-01')] }
  showBenchModal.value = true
}

function equipmentLabel(type) {
  return ({ POWER_SUPPLY: 'Power supply', OSCILLOSCOPE: 'Oscilloscope', RELAY_CARD: 'Carte relais', OTHER: 'Autre' })[type] || type
}

async function openBenchDetails(bench) {
  page.value = 'bench-detail'
  benchDetails.value = bench
  if (apiOffline.value) return
  try { benchDetails.value = await api(`/test-benches/${bench.id}`) }
  catch { notify('Impossible de charger le banc de test') }
}

function addEquipment(type = 'OTHER') { benchForm.value.equipment.push(emptyEquipment(type)) }
function addTerminal() { benchForm.value.terminals.push(emptyTerminal(`X1-${String(benchForm.value.terminals.length + 1).padStart(2, '0')}`)) }

async function saveBench() {
  try {
    if (apiOffline.value) {
      const localBench = { id: editingBench.value?.id || Date.now(), ...benchForm.value, equipmentCount: benchForm.value.equipment.length, terminalCount: benchForm.value.terminals.length, relayCount: benchForm.value.equipment.filter(item => item.equipmentType === 'RELAY_CARD').reduce((sum, item) => sum + Number(item.quantity || 1) * Number(item.channelCount || 1), 0) }
      if (editingBench.value) Object.assign(editingBench.value, localBench); else benches.value.unshift(localBench)
    } else {
      const saved = await api(editingBench.value ? `/test-benches/${editingBench.value.id}` : '/test-benches', { method: editingBench.value ? 'PUT' : 'POST', body: JSON.stringify(benchForm.value) })
      benchDetails.value = saved
    }
    showBenchModal.value = false; await loadData(); notify('Banc de test enregistré')
  } catch { notify('Impossible d’enregistrer le banc de test') }
}

async function deleteBench(bench) {
  if (!confirm(`Supprimer ${bench.name} ?`)) return
  if (!apiOffline.value) await api(`/test-benches/${bench.id}`, { method: 'DELETE' })
  benches.value = benches.value.filter(item => item.id !== bench.id)
  if (page.value === 'bench-detail') page.value = 'benches'
  notify('Banc de test supprimé')
}

async function openProjectDetails(project) {
  projectDetails.value = project
  projectActivity.value = []
  page.value = 'project-detail'
  if (apiOffline.value) {
    projectActivity.value = [{ action: 'UPDATED', details: 'Dernière information disponible dans la maquette.', actorName: 'Alex Martin', createdAt: project.updatedAt }]
    await loadFiles(project.documentationPath)
    return
  }
  try {
    const [details, activity] = await Promise.all([api(`/projects/${project.id}`), api(`/projects/${project.id}/activity`)]);
    projectDetails.value = details
    projectActivity.value = activity
    await loadFiles(details.documentationPath)
  } catch { notify('Impossible de charger les détails du projet'); await loadFiles(project.documentationPath) }
}

function backToProjects() { page.value = 'projects' }

function switchUser() {
  setCurrentUserId(currentUserId.value)
  notify(`Utilisateur actif : ${activeUser.value.displayName}`)
}

function formatDate(value) {
  if (!value) return '—'
  return new Intl.DateTimeFormat('fr-CA', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))
}

function activityLabel(action) {
  return ({ CREATED: 'Projet créé', UPDATED: 'Projet modifié' })[action] || action
}

async function saveProject() {
  try {
    if (apiOffline.value) {
      if (editingProject.value) Object.assign(editingProject.value, projectForm.value)
      else projects.value.unshift({ ...projectForm.value, id: Date.now(), documentationPath: `projets/${projectForm.value.projectNumber}` })
    } else await api(editingProject.value ? `/projects/${editingProject.value.id}` : '/projects', { method: editingProject.value ? 'PUT' : 'POST', body: JSON.stringify(projectForm.value) })
    showProjectModal.value = false; await loadData(); notify('Projet enregistré')
  } catch { notify('Impossible d’enregistrer le projet') }
}

async function deleteProject(project) {
  if (!confirm(`Supprimer ${project.projectNumber} ?`)) return
  if (!apiOffline.value) await api(`/projects/${project.id}`, { method: 'DELETE' })
  projects.value = projects.value.filter(item => item.id !== project.id); notify('Projet supprimé')
}

function openProjectDocuments(project) { page.value = 'documents'; loadFiles(project.documentationPath) }

async function openQuoteModal(quote = null, product = null, bench = null) {
  editingQuote.value = quote
  if (quote && !apiOffline.value) {
    const detail = await api(`/test-quotes/${quote.id}`)
    quoteForm.value = { productId: detail.productId, benchId: detail.benchId, templateId: detail.templateId, name: detail.name, description: detail.description || '', status: detail.status, references: detail.references || [], steps: detail.steps || [] }
    quoteEquipmentSummary.value = await api(`/test-quotes/${quote.id}/equipment-summary`).catch(() => null)
  } else {
    quoteEquipmentSummary.value = null
    quoteForm.value = { productId: product?.id || productDetails.value?.id || products.value[0]?.id || null, benchId: bench?.id || null, templateId: templates.value[0]?.id || null, name: '', description: '', status: 'DRAFT', references: [{ type: 'Megatech', value: '' }, { type: 'BRP', value: '' }], steps: [emptyStep()] }
  }
  showQuoteModal.value = true
}

function addQuoteStep() { quoteForm.value.steps.push(emptyStep(quoteForm.value.steps.length + 1)) }
function addQuoteReference() { quoteForm.value.references.push({ type: 'Autre', value: '' }) }

async function saveQuote() {
  try {
    if (apiOffline.value) {
      const product = products.value.find(item => Number(item.id) === Number(quoteForm.value.productId))
      const localQuote = { id: editingQuote.value?.id || Date.now(), ...quoteForm.value, productNumber: product?.productNumber, productName: product?.name, projectId: product?.projectId, projectNumber: product?.projectNumber, projectName: product?.projectName, benchName: benches.value.find(item => item.id === quoteForm.value.benchId)?.name, templateName: templates.value.find(item => item.id === quoteForm.value.templateId)?.name || 'GoogleTest standard', stepCount: quoteForm.value.steps.length }
      if (editingQuote.value) Object.assign(editingQuote.value, localQuote); else quotes.value.unshift(localQuote)
    } else await api(editingQuote.value ? `/test-quotes/${editingQuote.value.id}` : '/test-quotes', { method: editingQuote.value ? 'PUT' : 'POST', body: JSON.stringify(quoteForm.value) })
    showQuoteModal.value = false; await loadData(); notify('Devis enregistré')
  } catch { notify('Impossible d’enregistrer le devis') }
}

async function generateCpp(quote) {
  if (apiOffline.value) return notify('Mode présentation : génération C++ simulée')
  const response = await fetch(`${API_URL}/test-quotes/${quote.id}/generate-cpp`, { method: 'POST' }); const blob = await response.blob(); const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a'); anchor.href = url; anchor.download = `test_quote_${quote.id}.cpp`; anchor.click(); URL.revokeObjectURL(url); notify('Fichier C++ généré')
}

async function generatePdf(quote) {
  if (apiOffline.value) return notify('Mode présentation : génération PDF simulée')
  const response = await fetch(`${API_URL}/test-quotes/${quote.id}/generate-pdf`, { method: 'POST' })
  const blob = await response.blob(); const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a'); anchor.href = url; anchor.download = `devis_verification_${quote.id}.pdf`; anchor.click(); URL.revokeObjectURL(url); notify('PDF généré')
}

function openTemplateModal(template = null) {
  editingTemplate.value = template
  templateForm.value = template ? { name: template.name, description: template.description || '', language: template.language || 'CPP', content: template.content } : { name: '', description: '', language: 'CPP', content: defaultTemplateContent() }
  showTemplateModal.value = true
}

async function saveTemplate() {
  try {
    if (apiOffline.value) {
      const localTemplate = { id: editingTemplate.value?.id || Date.now(), templateKey: 'CUSTOM', ...templateForm.value, system: false }
      if (editingTemplate.value) Object.assign(editingTemplate.value, localTemplate); else templates.value.push(localTemplate)
    } else await api(editingTemplate.value ? `/test-templates/${editingTemplate.value.id}` : '/test-templates', { method: editingTemplate.value ? 'PUT' : 'POST', body: JSON.stringify(templateForm.value) })
    showTemplateModal.value = false; await loadData(); notify('Template enregistré')
  } catch { notify('Impossible d’enregistrer le template') }
}

async function deleteTemplate(template) {
  if (template.system || !confirm(`Supprimer ${template.name} ?`)) return
  if (!apiOffline.value) await api(`/test-templates/${template.id}`, { method: 'DELETE' })
  templates.value = templates.value.filter(item => item.id !== template.id); notify('Template supprimé')
}

function notify(message) { toast.value = message; setTimeout(() => { toast.value = '' }, 2800) }
function statusLabel(status) { return ({ ACTIVE: 'Actif', ARCHIVED: 'Archivé', IN_PROGRESS: 'En cours', DRAFT: 'Brouillon' })[status] || status }
function goTo(id) { page.value = id; if (id === 'documents') loadFiles('') }
onMounted(loadData)
</script>

<template>
  <div class="app-shell">
    <aside class="sidebar"><div class="brand"><div class="brand-mark">M</div><div><strong>MegaFinder</strong><small>LAB OPERATIONS</small></div></div><div class="workspace-label">ESPACE DE TRAVAIL</div><nav><button v-for="item in navItems" :key="item.id" :class="{ active: page === item.id }" @click="goTo(item.id)"><span class="nav-icon">{{ item.icon }}</span>{{ item.label }}</button></nav><div class="sidebar-bottom"><button class="team-link" :class="{ active: page === 'team' }" @click="page = 'team'"><span class="nav-icon">◎</span>Équipe & accès</button><div class="user-card"><div class="avatar">{{ activeUser.displayName.split(' ').map(part => part[0]).join('').slice(0, 2) }}</div><div><strong>{{ activeUser.displayName }}</strong><small>{{ activeUser.role }}</small></div></div></div></aside>
    <main class="main-content">
      <header class="topbar"><div class="breadcrumbs"><span>MegaFinder</span><b>/</b><strong>{{ navItems.find(item => item.id === page)?.label || (page === 'project-detail' ? 'Détail du projet' : 'Équipe & accès') }}</strong></div><div class="top-actions"><span class="status-dot"></span><span class="sync-label">{{ apiOffline ? 'Mode démo' : 'Synchronisé' }}</span><select class="user-switcher" v-model="currentUserId" @change="switchUser"><option v-for="user in users" :key="user.id" :value="Number(user.id)">{{ user.displayName }}</option></select></div></header>
      <div v-if="apiOffline" class="demo-banner">Mode présentation actif — les données affichées sont une maquette locale.</div>
      <section v-if="page === 'dashboard'" class="page"><div class="page-heading"><div><p class="eyebrow">PILOTAGE</p><h1>Bonjour {{ activeUser.displayName.split(' ')[0] }}</h1><p class="subtitle">Voici l’état de vos opérations de test aujourd’hui.</p></div><button class="primary-button" @click="openProjectModal()">＋ Nouveau projet</button></div><div class="metric-grid"><div class="metric-card"><strong>{{ summary.projects }}</strong><span>Projets actifs</span></div><div class="metric-card"><strong>{{ summary.activeQuotes }}</strong><span>Devis en cours</span></div><div class="metric-card"><strong>{{ summary.documents }}</strong><span>Documents suivis</span></div><div class="metric-card"><strong>{{ summary.teamMembers }}</strong><span>Membres de l’équipe</span></div></div></section>
      <section v-else-if="page === 'projects'" class="page"><div class="page-heading"><div><p class="eyebrow">PILOTAGE</p><h1>Projets</h1><p class="subtitle">Cliquez sur un projet pour voir son historique.</p></div><button class="primary-button" @click="openProjectModal()">＋ Nouveau projet</button></div><div class="toolbar"><div class="search-box">⌕<input v-model="search" placeholder="Rechercher un projet..." /></div><span class="result-count">{{ filteredProjects.length }} projets</span></div><div class="panel table-panel"><table><thead><tr><th>PROJET</th><th>CONTACT</th><th>DOSSIER</th><th>STATUT</th><th></th></tr></thead><tbody><tr v-for="project in filteredProjects" :key="project.id"><td><button class="project-link" @click="openProjectDetails(project)"><span class="project-avatar">{{ project.projectNumber.slice(-2) }}</span><span><strong>{{ project.name }}</strong><small>{{ project.projectNumber }}</small></span></button></td><td>{{ project.contactPerson || '—' }}</td><td class="description-cell">{{ project.documentationPath }}</td><td><span class="badge" :class="project.status.toLowerCase()">{{ statusLabel(project.status) }}</span></td><td class="actions"><button @click="openProjectDetails(project)">Détails</button><button @click="openProjectDocuments(project)">Docs</button><button @click="openProjectModal(project)">Modifier</button><button class="danger-link" @click="deleteProject(project)">Supprimer</button></td></tr></tbody></table></div></section>
      <section v-else-if="page === 'project-detail' && projectDetails" class="page project-detail-page"><div class="detail-page-heading"><button class="back-button" @click="backToProjects">← Projets</button><div class="detail-heading-actions"><button class="filter-button" @click="openProjectModal(projectDetails)">Modifier</button><button class="primary-button" @click="openProjectDocuments(projectDetails)">Ouvrir la documentation</button></div></div><div class="project-hero"><div><p class="eyebrow">FICHE PROJET</p><div class="project-title-line"><span class="project-avatar large">{{ projectDetails.projectNumber.slice(-2) }}</span><div><h1>{{ projectDetails.name }}</h1><span class="detail-project-number">{{ projectDetails.projectNumber }}</span></div></div><p class="subtitle">{{ projectDetails.description || 'Aucune description pour ce projet.' }}</p></div><span class="badge" :class="projectDetails.status.toLowerCase()">{{ statusLabel(projectDetails.status) }}</span></div><div class="project-detail-grid"><div class="project-main-column"><section class="panel detail-panel"><div class="panel-heading"><div><h2>Documentation</h2><p>{{ projectDetails.documentationPath }}</p></div><button class="text-button" @click="loadFiles(projectDetails.documentationPath)">Actualiser</button></div><div class="quick-files"><div v-for="file in files.slice(0, 5)" :key="file.path" class="quick-file" @click="file.type === 'directory' ? loadFiles(file.path) : openFile(file)"><div class="file-icon" :class="file.type">{{ file.type === 'directory' ? '▰' : '▤' }}</div><div><strong>{{ file.name }}</strong><small>{{ file.type === 'directory' ? 'Dossier' : file.extension.toUpperCase() + ' · fichier local' }}</small></div><span>→</span></div><div v-if="!files.length" class="empty-state compact-empty">Aucun fichier dans ce dossier.</div></div></section><section class="panel detail-panel"><div class="panel-heading"><div><h2>Produits</h2><p>{{ projectProducts.length }} produit{{ projectProducts.length > 1 ? 's' : '' }} lié{{ projectProducts.length > 1 ? 's' : '' }} à ce projet</p></div><button class="text-button" @click="openProductModal(null, projectDetails)">＋ Nouveau produit</button></div><div class="linked-quotes"><div v-for="product in projectProducts" :key="product.id" class="linked-quote"><div><strong>{{ product.productNumber }} · {{ product.name }}</strong><small>{{ product.quoteCount || 0 }} devis · {{ product.contactCount || 0 }} contacts</small></div><div class="linked-quote-actions"><button class="filter-button compact-button" @click="openProductDetails(product)">Ouvrir</button><button class="outline-button compact-button" @click="openProductModal(product)">Modifier</button></div></div><div v-if="!projectProducts.length" class="empty-state compact-empty">Aucun produit lié à ce projet.</div></div></section></div><aside class="project-side-column"><section class="panel detail-panel"><div class="panel-heading"><div><h2>Dernière activité</h2><p>{{ projectActivity.length }} événement{{ projectActivity.length > 1 ? 's' : '' }}</p></div></div><div class="activity-list"><div v-for="activity in projectActivity.slice(0, 5)" :key="activity.id || `${activity.action}-${activity.createdAt}`" class="project-activity"><div class="activity-mark">{{ activity.action === 'CREATED' ? '＋' : '↻' }}</div><div><strong>{{ activityLabel(activity.action) }}</strong><p>{{ activity.details }}</p><small>{{ activity.actorName || 'Utilisateur inconnu' }} · {{ formatDate(activity.createdAt) }}</small></div></div><div v-if="!projectActivity.length" class="empty-state compact-empty">Aucune activité disponible.</div></div></section><section class="panel detail-panel project-info"><h2>Informations</h2><dl><dt>Contact</dt><dd>{{ projectDetails.contactPerson || '—' }}</dd><dt>Dossier</dt><dd>{{ projectDetails.documentationPath }}</dd><dt>Dernière modification</dt><dd>{{ formatDate(projectDetails.updatedAt) }}</dd></dl></section></aside></div></section>
      <section v-else-if="page === 'products'" class="page"><div class="page-heading"><div><p class="eyebrow">PRODUITS</p><h1>Produits</h1><p class="subtitle">Chaque produit regroupe sa présentation, son matériel et ses devis de vérification.</p></div><button class="primary-button" @click="openProductModal()">＋ Nouveau produit</button></div><div class="product-grid"><div v-for="product in products" :key="product.id" class="product-card"><div class="product-card-top"><span class="product-mark">◈</span><span class="badge active">{{ product.quoteCount || 0 }} devis</span></div><h3>{{ product.productNumber }}</h3><h4>{{ product.name }}</h4><p>{{ product.description || 'Aucune description' }}</p><small>{{ product.projectNumber }} · {{ product.projectName }}</small><div class="product-card-stats"><span>{{ product.contactCount || 0 }} contacts</span><span>{{ product.quoteCount || 0 }} vérifications</span></div><div class="product-card-actions"><button class="filter-button" @click="openProductDetails(product)">Ouvrir</button><button class="outline-button" @click="openProductModal(product)">Modifier</button><button class="danger-link" @click="deleteProduct(product)">Supprimer</button></div></div><div class="product-card new-card" @click="openProductModal()"><div class="new-plus">＋</div><strong>Créer un produit</strong><p>Ajouter sa fiche, ses contacts et ses caractéristiques.</p></div></div></section>
      <section v-else-if="page === 'product-detail' && productDetails" class="page product-detail-page"><div class="detail-page-heading"><button class="back-button" @click="page = 'products'">← Produits</button><div class="detail-heading-actions"><button class="filter-button" @click="openProductModal(productDetails)">Modifier</button><button class="primary-button" @click="openQuoteModal(null, productDetails)">＋ Nouveau devis</button></div></div><div class="product-hero"><div><p class="eyebrow">FICHE PRODUIT</p><h1>{{ productDetails.name }}</h1><span class="detail-project-number">{{ productDetails.productNumber }}</span><p class="subtitle">{{ productDetails.description || 'Aucune description pour ce produit.' }}</p></div><span class="badge active">{{ productDetails.projectNumber }}</span></div><div class="product-section-grid"><section class="panel detail-panel"><div class="panel-heading"><div><h2>Présentation du produit</h2><p>{{ productDetails.presentation || 'Aucune présentation définie.' }}</p></div></div><div class="image-grid"><div v-for="image in productDetails.presentationImages" :key="image" class="image-tile"><span>▧</span><strong>{{ image }}</strong></div><div v-if="!productDetails.presentationImages?.length" class="empty-state">Aucune image de présentation.</div></div><div class="contacts-list"><h3>Contacts produit</h3><div v-for="contact in productDetails.contacts" :key="contact.id || contact.name" class="contact-row"><strong>{{ contact.name }}</strong><span>{{ contact.role || 'Rôle non défini' }}</span><small>{{ contact.email || contact.phone || 'Coordonnées non définies' }}</small></div></div></section><section class="panel detail-panel"><div class="panel-heading"><div><h2>Assemblage</h2><p>Éléments et séquence de montage</p></div></div><div class="assembly-copy"><h3>Éléments utilisés</h3><p>{{ productDetails.assemblyElements || 'Aucun élément défini.' }}</p><h3>Étapes d’assemblage</h3><p>{{ productDetails.assemblySteps || 'Aucune étape définie.' }}</p></div></section><section class="panel detail-panel"><div class="panel-heading"><div><h2>Boîtier et pinout</h2><p>{{ productDetails.enclosurePinout || 'Aucun pinout défini.' }}</p></div></div><div class="image-grid"><div v-for="image in productDetails.enclosureImages" :key="image" class="image-tile"><span>▧</span><strong>{{ image }}</strong></div><div v-if="!productDetails.enclosureImages?.length" class="empty-state">Aucune image du boîtier.</div></div></section><section class="panel detail-panel"><div class="panel-heading"><div><h2>PCB</h2><p>{{ productDetails.pcbSpecifications || 'Aucune caractéristique définie.' }}</p></div></div><div class="image-grid"><div v-for="image in productDetails.pcbImages" :key="image" class="image-tile"><span>▧</span><strong>{{ image }}</strong></div><div v-if="!productDetails.pcbImages?.length" class="empty-state">Aucune image du PCB.</div></div></section></div><section class="panel detail-panel verification-panel"><div class="panel-heading"><div><h2>Vérification</h2><p>Les devis sont regroupés par type de test et reliés à un template par étape.</p></div><div class="detail-heading-actions"><button class="outline-button" @click="productDetails.quotes?.[0] && generatePdf(productDetails.quotes[0])">Générer PDF</button><button class="primary-button" @click="openQuoteModal(null, productDetails)">＋ Nouveau devis</button></div></div><div class="linked-quotes"><div v-for="quote in productDetails.quotes" :key="quote.id" class="linked-quote"><div><strong>{{ quote.name }}</strong><small>{{ quote.stepCount }} étapes · {{ quote.status }}</small></div><div class="linked-quote-actions"><button class="filter-button compact-button" @click="openQuoteModal(quote)">Modifier</button><button class="outline-button compact-button" @click="generateCpp(quote)">C++</button><button class="outline-button compact-button" @click="generatePdf(quote)">PDF</button><button class="outline-button compact-button" @click="decodeQuoteEquipment(quote)">Décoder</button></div><div v-if="equipmentSummaries[quote.id]" class="equipment-summary"><strong>Équipement requis</strong><span v-if="!equipmentSummaries[quote.id].requirements?.length">Aucun instrument explicite dans les étapes.</span><span v-for="requirement in equipmentSummaries[quote.id].requirements" :key="requirement.equipmentType" :class="{ 'summary-missing': requirement.status === 'MISSING' }">{{ requirement.label }} : {{ requirement.required }} {{ requirement.unit }} requis · {{ requirement.available }} disponible{{ requirement.available > 1 ? 's' : '' }}</span><small>Banc : {{ equipmentSummaries[quote.id].benchName || 'non sélectionné' }}</small></div></div><div v-if="!productDetails.quotes?.length" class="empty-state compact-empty">Aucun devis pour ce produit.</div></div></section></section>
      <section v-else-if="page === 'benches'" class="page"><div class="page-heading"><div><p class="eyebrow">INFRASTRUCTURE DE TEST</p><h1>Bancs de test</h1><p class="subtitle">Définissez les instruments, les relais et le bornier disponibles.</p></div><button class="primary-button" @click="openBenchModal()">＋ Nouveau banc</button></div><div class="bench-grid"><div v-for="bench in benches" :key="bench.id" class="bench-card"><div class="bench-card-top"><span class="bench-icon">⌘</span><span class="badge active">{{ bench.relayCount || 0 }} relais</span></div><h3>{{ bench.name }}</h3><p>{{ bench.description || 'Aucune description' }}</p><small>{{ bench.location || 'Emplacement non défini' }}</small><div class="bench-stats"><span><strong>{{ bench.equipmentCount || 0 }}</strong> équipements</span><span><strong>{{ bench.terminalCount || 0 }}</strong> bornes</span></div><div class="bench-card-actions"><button class="filter-button" @click="openBenchDetails(bench)">Ouvrir</button><button class="outline-button" @click="openBenchModal(bench)">Modifier</button><button class="danger-link" @click="deleteBench(bench)">Supprimer</button></div></div><div class="bench-card new-card" @click="openBenchModal()"><div class="new-plus">＋</div><strong>Créer un banc</strong><p>Ajouter alimentations, oscilloscope, relais et bornier.</p></div></div></section>
      <section v-else-if="page === 'bench-detail' && benchDetails" class="page bench-detail-page"><div class="detail-page-heading"><button class="back-button" @click="page = 'benches'">← Bancs de test</button><div class="detail-heading-actions"><button class="filter-button" @click="openBenchModal(benchDetails)">Modifier</button><button class="primary-button" @click="openQuoteModal(null, null, benchDetails)">＋ Nouveau devis</button></div></div><div class="bench-hero"><div><p class="eyebrow">BANC DE TEST</p><h1>{{ benchDetails.name }}</h1><p class="subtitle">{{ benchDetails.description || 'Aucune description pour ce banc.' }}</p><small>{{ benchDetails.location || 'Emplacement non défini' }}</small></div><span class="bench-hero-count">{{ benchDetails.relayCount || 0 }} relais</span></div><div class="bench-detail-grid"><section class="panel detail-panel"><div class="panel-heading"><div><h2>Équipements</h2><p>Ressources disponibles sur ce banc</p></div></div><div class="equipment-grid"><div v-for="equipment in benchDetails.equipment" :key="equipment.id || equipment.name" class="equipment-card"><span class="equipment-type">{{ equipmentLabel(equipment.equipmentType) }}</span><h3>{{ equipment.name }}</h3><p v-if="equipment.equipmentType === 'POWER_SUPPLY'">{{ equipment.voltageMin }}–{{ equipment.voltageMax }} V · {{ equipment.currentMax }} A max</p><p v-else>{{ equipment.channelCount || 1 }} voies · quantité {{ equipment.quantity || 1 }}</p><small>{{ equipment.notes || 'Aucune note' }}</small></div></div><div v-if="!benchDetails.equipment?.length" class="empty-state">Aucun équipement défini.</div></section><section class="panel detail-panel"><div class="panel-heading"><div><h2>Vue du bornier</h2><p>{{ benchDetails.terminals?.length || 0 }} connexions configurées</p></div></div><div class="terminal-grid"><div v-for="terminal in benchDetails.terminals" :key="terminal.id || terminal.terminalLabel" class="terminal-card"><div class="terminal-label">{{ terminal.terminalLabel }}</div><div><strong>{{ terminal.pinName || 'Pin non nommé' }}</strong><small>{{ terminal.signalType || 'Type non défini' }}</small><p>{{ terminal.description || 'Aucune description' }}</p></div><span v-if="terminal.relayReference" class="relay-tag">{{ terminal.relayReference }}</span></div></div><div v-if="!benchDetails.terminals?.length" class="empty-state">Aucune borne définie.</div></section></div></section>
      <section v-else-if="page === 'templates'" class="page"><div class="page-heading"><div><p class="eyebrow">GÉNÉRATION C++</p><h1>Templates de tests</h1><p class="subtitle">Modifiez le contenu utilisé pour générer les fichiers unitaires.</p></div><button class="primary-button" @click="openTemplateModal()">＋ Nouveau template</button></div><div class="template-grid"><div v-for="template in templates" :key="template.id" class="quote-card"><span class="badge active">{{ template.language }}</span><h3>{{ template.name }}</h3><p>{{ template.description || 'Aucune description' }}</p><small>Variables : {{ templateTokens }}</small><div class="quote-card-actions"><button class="filter-button" @click="openTemplateModal(template)">Modifier</button><button v-if="!template.system" class="danger-link" @click="deleteTemplate(template)">Supprimer</button></div></div></div></section>
      <section v-else-if="page === 'documents'" class="page"><div class="page-heading"><div><p class="eyebrow">ESPACE LOCAL</p><h1>Documentation</h1><p class="subtitle">Dossier courant : {{ currentFolder || 'racine' }}</p></div><button class="primary-button" @click="loadFiles()">↻ Actualiser</button></div><div class="path-bar"><b>/ documentation</b><span v-if="currentFolder">/ {{ currentFolder }}</span><button v-if="currentFolder" @click="loadFiles('')">Revenir à la racine</button></div><div class="panel files-panel"><div class="files-heading"><div><h2>Fichiers disponibles</h2><p>Le contenu reste sur votre disque local.</p></div><span>{{ files.length }} éléments</span></div><div v-for="file in files" :key="file.path" class="file-row" @dblclick="openFile(file)"><div class="file-icon" :class="file.type">{{ file.type === 'directory' ? '▰' : '▤' }}</div><div><strong>{{ file.name }}</strong><small>{{ file.type === 'directory' ? 'Dossier' : file.extension.toUpperCase() + ' · fichier local' }}</small></div><button v-if="file.type === 'directory'" @click="loadFiles(file.path)">Ouvrir →</button><div v-else class="file-actions"><button @click.stop="openFile(file)">Ouvrir ↗</button><button @click.stop="copyFilePath(file)">Copier le chemin</button></div></div><div v-if="!files.length" class="empty-state">Aucun fichier dans ce dossier.</div></div></section>
      <section v-else class="page"><div class="page-heading"><div><p class="eyebrow">ADMINISTRATION</p><h1>Équipe & accès</h1><p class="subtitle">Gérez les rôles et les droits complémentaires.</p></div></div><div class="panel table-panel"><table><thead><tr><th>MEMBRE</th><th>RÔLE</th><th>PERMISSIONS</th><th>STATUT</th></tr></thead><tbody><tr v-for="user in users" :key="user.id"><td><strong>{{ user.displayName }}</strong><small>{{ user.email }}</small></td><td>{{ user.role }}</td><td>{{ user.extraPermissions.join(', ') }}</td><td>Actif</td></tr></tbody></table></div></section>
    </main>
    <div v-if="showProjectModal" class="modal-backdrop" @click.self="showProjectModal = false"><div class="modal"><div class="modal-heading"><h2>{{ editingProject ? 'Modifier le projet' : 'Nouveau projet' }}</h2><button @click="showProjectModal = false">×</button></div><label>Numéro du projet<input v-model="projectForm.projectNumber" placeholder="MF-2402" /></label><label>Nom du projet<input v-model="projectForm.name" placeholder="Nom du projet" /></label><label>Personne à contacter<input v-model="projectForm.contactPerson" placeholder="Nom du contact" /></label><label>Description<textarea v-model="projectForm.description" rows="4"></textarea></label><div class="modal-actions"><button class="filter-button" @click="showProjectModal = false">Annuler</button><button class="primary-button" @click="saveProject">Enregistrer</button></div></div></div>
    <div v-if="showProjectDetails" class="modal-backdrop" @click.self="showProjectDetails = false"><div class="modal project-detail-modal"><div class="modal-heading"><div><p class="eyebrow">FICHE PROJET</p><h2>{{ projectDetails?.name }}</h2><span class="detail-project-number">{{ projectDetails?.projectNumber }}</span></div><button @click="showProjectDetails = false">×</button></div><div class="project-detail-summary"><div><span>Dernière modification</span><strong>{{ formatDate(projectDetails?.updatedAt) }}</strong></div><div><span>Dernière action</span><strong>{{ projectActivity.length ? activityLabel(projectActivity[0].action) : '—' }}</strong><small v-if="projectActivity.length">par {{ projectActivity[0].actorName || 'Utilisateur inconnu' }}</small></div></div><p class="detail-description">{{ projectDetails?.description || 'Aucune description.' }}</p><div class="activity-heading"><h3>Historique</h3><span>{{ projectActivity.length }} événement{{ projectActivity.length > 1 ? 's' : '' }}</span></div><div class="activity-list"><div v-for="activity in projectActivity" :key="activity.id || `${activity.action}-${activity.createdAt}`" class="project-activity"><div class="activity-mark">{{ activity.action === 'CREATED' ? '＋' : '↻' }}</div><div><strong>{{ activityLabel(activity.action) }}</strong><p>{{ activity.details }}</p><small>{{ activity.actorName || 'Utilisateur inconnu' }} · {{ formatDate(activity.createdAt) }}</small></div></div><div v-if="!projectActivity.length" class="empty-state">Aucun historique disponible.</div></div><div class="modal-actions"><button class="filter-button" @click="showProjectDetails = false">Fermer</button><button class="primary-button" @click="showProjectDetails = false; openProjectModal(projectDetails)">Modifier le projet</button></div></div></div>
    <div v-if="showProductModal" class="modal-backdrop" @click.self="showProductModal = false"><div class="modal product-modal"><div class="modal-heading"><div><p class="eyebrow">FICHE PRODUIT</p><h2>{{ editingProduct ? 'Modifier le produit' : 'Nouveau produit' }}</h2></div><button @click="showProductModal = false">×</button></div><label>Projet<select v-model="productForm.projectId"><option v-for="project in projects" :key="project.id" :value="project.id">{{ project.projectNumber }} · {{ project.name }}</option></select></label><label>Numéro du produit<input v-model="productForm.productNumber" placeholder="ECU-2401-P1" /></label><label>Nom du produit<input v-model="productForm.name" placeholder="Contrôleur ECU principal" /></label><label>Description<textarea v-model="productForm.description" rows="2"></textarea></label><label>Présentation<textarea v-model="productForm.presentation" rows="3"></textarea></label><label>Éléments utilisés<textarea v-model="productForm.assemblyElements" rows="3" placeholder="Boîtier
PCB
Connecteurs"></textarea></label><label>Étapes d’assemblage<textarea v-model="productForm.assemblySteps" rows="3" placeholder="1. Installer le PCB
2. Fermer le boîtier"></textarea></label><label>Images produit <small>(un chemin local par ligne)</small><textarea v-model="productForm.presentationImagesText" rows="2" placeholder="images/produit-avant.png"></textarea></label><label>Images boîtier <small>(un chemin local par ligne)</small><textarea v-model="productForm.enclosureImagesText" rows="2"></textarea></label><label>Pinout du boîtier<textarea v-model="productForm.enclosurePinout" rows="3" placeholder="TP5 = alimentation
TP9 = GND"></textarea></label><label>Images PCB <small>(un chemin local par ligne)</small><textarea v-model="productForm.pcbImagesText" rows="2"></textarea></label><label>Caractéristiques PCB<textarea v-model="productForm.pcbSpecifications" rows="2" placeholder="4 couches · FR-4 · 12 V nominal"></textarea></label><div class="form-section-heading"><strong>Contacts et rôles</strong><button class="text-button" @click="addProductContact">＋ Ajouter</button></div><div v-for="(contact, index) in productForm.contacts" :key="index" class="contact-form"><div class="form-row"><input v-model="contact.name" placeholder="Nom" /><input v-model="contact.role" placeholder="Rôle" /><button class="remove-button" @click="productForm.contacts.splice(index, 1)">×</button></div><div class="form-row"><input v-model="contact.email" placeholder="Courriel" /><input v-model="contact.phone" placeholder="Téléphone" /></div></div><div class="modal-actions"><button class="filter-button" @click="showProductModal = false">Annuler</button><button class="primary-button" @click="saveProduct">Enregistrer</button></div></div></div>
    <div v-if="showBenchModal" class="modal-backdrop" @click.self="showBenchModal = false"><div class="modal bench-modal"><div class="modal-heading"><div><p class="eyebrow">INFRASTRUCTURE</p><h2>{{ editingBench ? 'Modifier le banc' : 'Nouveau banc de test' }}</h2></div><button @click="showBenchModal = false">×</button></div><label>Nom du banc<input v-model="benchForm.name" placeholder="Banc ECU principal" /></label><label>Emplacement<input v-model="benchForm.location" placeholder="Laboratoire A · Poste 01" /></label><label>Description<textarea v-model="benchForm.description" rows="2"></textarea></label><div class="form-section-heading"><strong>Équipements</strong><button class="text-button" @click="addEquipment('POWER_SUPPLY')">＋ Ajouter</button></div><div v-for="(equipment, index) in benchForm.equipment" :key="index" class="equipment-form"><div class="form-row"><select v-model="equipment.equipmentType"><option value="POWER_SUPPLY">Power supply</option><option value="OSCILLOSCOPE">Oscilloscope</option><option value="RELAY_CARD">Carte relais</option><option value="OTHER">Autre</option></select><input v-model="equipment.name" placeholder="Nom de l'équipement" /><input v-model.number="equipment.quantity" type="number" min="1" placeholder="Qté" /><button class="remove-button" @click="benchForm.equipment.splice(index, 1)">×</button></div><div class="form-row equipment-values"><input v-model.number="equipment.channelCount" type="number" min="1" placeholder="Voies" /><input v-model.number="equipment.voltageMin" type="number" placeholder="V min" /><input v-model.number="equipment.voltageMax" type="number" placeholder="V max" /><input v-model.number="equipment.currentMax" type="number" placeholder="A max" /></div><input v-model="equipment.notes" placeholder="Notes" /></div><div class="form-section-heading"><strong>Bornier et liaisons</strong><button class="text-button" @click="addTerminal">＋ Ajouter une borne</button></div><div v-for="(terminal, index) in benchForm.terminals" :key="index" class="terminal-form"><div class="form-row"><input v-model="terminal.terminalLabel" placeholder="Borne X1-01" /><input v-model="terminal.pinName" placeholder="Nom du pin" /><input v-model="terminal.signalType" placeholder="Type de signal" /><button class="remove-button" @click="benchForm.terminals.splice(index, 1)">×</button></div><div class="form-row"><input v-model="terminal.description" placeholder="Fonction / description" /><input v-model="terminal.relayReference" placeholder="Relais associé, ex. K1" /></div></div><div class="modal-actions"><button class="filter-button" @click="showBenchModal = false">Annuler</button><button class="primary-button" @click="saveBench">Enregistrer</button></div></div></div>
    <div v-if="showQuoteModal" class="modal-backdrop" @click.self="showQuoteModal = false"><div class="modal quote-modal structured-quote-modal"><div class="modal-heading"><div><p class="eyebrow">VÉRIFICATION</p><h2>{{ editingQuote ? 'Modifier le devis' : 'Nouveau devis' }}</h2></div><button @click="showQuoteModal = false">×</button></div><label>Produit<select v-model="quoteForm.productId"><option v-for="product in products" :key="product.id" :value="product.id">{{ product.productNumber }} · {{ product.name }}</option></select></label><label>Nom du devis<input v-model="quoteForm.name" placeholder="Validation électrique - Test B" /></label><label>Description<textarea v-model="quoteForm.description" rows="2"></textarea></label><div class="form-section-heading"><strong>Numéros de référence</strong><button class="text-button" @click="addQuoteReference">＋ Ajouter</button></div><div v-for="(reference, index) in quoteForm.references" :key="index" class="reference-form"><input v-model="reference.type" placeholder="Megatech, BRP, autre" /><input v-model="reference.value" placeholder="Numéro de devis" /><button class="remove-button" @click="quoteForm.references.splice(index, 1)">×</button></div><label>Banc de test<select v-model="quoteForm.benchId"><option :value="null">Aucun banc</option><option v-for="bench in benches" :key="bench.id" :value="bench.id">{{ bench.name }}</option></select></label><div class="step-editor"><div class="step-editor-heading"><strong>Section vérification</strong><button class="text-button" @click="addQuoteStep">＋ Ajouter une étape</button></div><div v-for="(step, index) in quoteForm.steps" :key="index" class="step-card"><div class="step-card-heading"><span class="step-number">{{ index + 1 }}</span><input class="step-order" v-model.number="step.stepNumber" type="number" min="1" placeholder="Étape" /><input class="step-order" v-model.number="step.subStep" type="number" min="1" placeholder="Sous" /><strong>Type de test</strong><select v-model="step.verificationType"><option value="B">B</option><option value="C">C</option><option value="D">D</option><option value="E">E</option><option value="ECT">ECT</option><option value="AUTRE">Autre</option></select></div><div class="step-line"><input v-model="step.startCondition" placeholder="Condition / alimentation, ex. 14 V 1 A sur TP5" /><input v-model="step.groundReference" placeholder="Référence GND, ex. TP9" /><input v-model="step.pinToTest" placeholder="Pin à mesurer, ex. TP5" /></div><div class="step-line step-hardware-line"><input v-model="step.testMethod" placeholder="Méthode : mettre +45 VDC via 5k1" /><input v-model.number="step.waitMs" type="number" placeholder="Wait ms" /><input v-model="step.requiredInstruments" placeholder="Instruments : scope, alim" /><select v-model="step.testTemplateId"><option :value="null">Template de mesure</option><option v-for="template in templates" :key="template.id" :value="template.id">{{ template.name }}</option></select></div><div class="step-line"><input v-model="step.measurementMethod" placeholder="Méthode de mesure : courant sur TP5" /><select v-model="step.measurementType"><option value="CURRENT">Courant</option><option value="VOLTAGE">Tension</option><option value="RESISTANCE">Résistance</option><option value="FREQUENCY">Fréquence</option><option value="DUTY_CYCLE">Duty cycle</option></select><input v-model="step.unit" placeholder="Unité mA / V" /><input v-model.number="step.expectedMin" type="number" placeholder="Balise min" /><input v-model.number="step.expectedMax" type="number" placeholder="Balise max" /></div><div class="step-line step-hardware-line"><input v-model="step.powerSupplyName" placeholder="Power supply" /><input v-model.number="step.supplyVoltage" type="number" placeholder="Tension V" /><input v-model.number="step.supplyCurrent" type="number" placeholder="Courant A" /><input v-model="step.relayChannels" placeholder="Relais K1,K4" /><input v-model.number="step.relayDelayMs" type="number" placeholder="Délai relais ms" /></div></div></div><div v-if="quoteEquipmentSummary" class="equipment-summary modal-summary"><strong>Décodage du banc</strong><span v-for="requirement in quoteEquipmentSummary.requirements" :key="requirement.equipmentType" :class="{ 'summary-missing': requirement.status === 'MISSING' }">{{ requirement.label }} : {{ requirement.required }} {{ requirement.unit }} requis · {{ requirement.available }} disponible{{ requirement.available > 1 ? 's' : '' }}</span></div><div class="modal-actions"><button class="filter-button" @click="showQuoteModal = false">Annuler</button><button class="primary-button" @click="saveQuote">Enregistrer le devis</button></div></div></div>
    <div v-if="showTemplateModal" class="modal-backdrop" @click.self="showTemplateModal = false"><div class="modal template-editor"><div class="modal-heading"><h2>{{ editingTemplate ? 'Modifier le template' : 'Nouveau template' }}</h2><button @click="showTemplateModal = false">×</button></div><p class="modal-help">Variables : {{ templateTokensFull }}.</p><label>Nom<input v-model="templateForm.name" placeholder="GoogleTest hardware" /></label><label>Description<input v-model="templateForm.description" /></label><label>Contenu C++<textarea v-model="templateForm.content" rows="16" spellcheck="false"></textarea></label><div class="modal-actions"><button class="filter-button" @click="showTemplateModal = false">Annuler</button><button class="primary-button" @click="saveTemplate">Enregistrer</button></div></div></div>
    <div v-if="toast" class="toast">✓ {{ toast }}</div>
  </div>
</template>
