ALTER TABLE projects ADD COLUMN documentation_path VARCHAR(240);

UPDATE projects
SET documentation_path = 'projets/' || project_number
WHERE documentation_path IS NULL;

ALTER TABLE projects ALTER COLUMN documentation_path SET NOT NULL;

CREATE TABLE test_templates (
    id BIGSERIAL PRIMARY KEY,
    template_key VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    description TEXT,
    language VARCHAR(30) NOT NULL DEFAULT 'CPP',
    content TEXT NOT NULL,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO test_templates (template_key, name, description, language, content, is_system)
VALUES (
    'DEFAULT',
    'GoogleTest standard',
    'Template C++ de base pour les devis de tests MegaFinder.',
    'CPP',
    $template$// Generated by MegaFinder - Test quote #{{QUOTE_ID}}
#include <gtest/gtest.h>

class {{TEST_CLASS}} : public ::testing::Test {};

{{STEPS}}$template$,
    TRUE
);

ALTER TABLE test_quotes ADD COLUMN template_id BIGINT REFERENCES test_templates(id) ON DELETE SET NULL;

UPDATE test_quotes
SET template_id = (SELECT id FROM test_templates WHERE template_key = 'DEFAULT')
WHERE template_id IS NULL;
